name: dev CI

on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install --save --legacy-peer-deps

      - name: Build
        run: |
          npm run build --if-present

      - name: Deploy to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTDEV }}
          username: ${{ secrets.USERDEV }}
          key: ${{ secrets.KEYDEV }}
          port: ${{ secrets.PORTDEV }}
          source: dist/
          target: /home/ubuntu/deploy/

      - name: Extract and deploy Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTDEV }}
          username: ${{ secrets.USERDEV }}
          key: ${{ secrets.KEYDEV }}
          port: ${{ secrets.PORTDEV }}
          script: |
            cd /home/ubuntu/deploy/
            mkdir dist
            cp -TR . dist/
            tar -xvf dist/deploy.tar -C /var/www/html/
            sudo apt-get update
            sudo apt-get install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx
